### ISSUE TITLE
Error on hierarchy of tags

### ISSUE THREAD

**Issue by AlexGunslinger** [eponce19/CodeTerminator#12]
Starter code:

<!DOCTYPE html>
<html>
<head>
  <title>My First Website</title>
</head>
<body>
  <header>
    <nav>
      <a href='about.html'>About</a>
      <a href='contact.html'>Contact</a>
    </nav>
  </header>
  <p>My index page</p>
</body>
</html>

Exercise:

<footer>
  <p>Please contact: </p><a href='mailto:joe@email.com'>joe@email.com</a>
</footer>

**Comment by eponce19** [comment]
Fixed in https://github.com/eponce19/CodeTerminator/commit/3751d3b8a30cd909714f3286022e5c70cbfbcf9e 
Update to 0.4.6
